       SUBROUTINE t4A_antisym(N0,N1,N2,N3,K1,K2,K3,K4,lvl,shift,
     & FockR,FockB,IntR,IntB,IntM,t1A,t1B,t2A,t2B,t2C,t3A,t3B,t3C,t3D,
     & iactocca,iactunoa,iactindq)
!    & t4A,t4B,t4C,t4D,t4E)
C
       INTEGER a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
       INTEGER iactocca,iactunoa,iactindq
       INTEGER iocca,iunoa
       INTEGER, ALLOCATABLE:: inDOcc(:,:,:,:)
       INTEGER, ALLOCATABLE:: indunocc(:,:,:,:)
!       INTEGER inDOcc(N0+1:N1,N0+1:N1,N0+1:N1,N0+1:N1)
!       INTEGER indunocc(N1+1:N3,N1+1:N3,N1+1:N3,N1+1:N3)
       REAL*8 shift,PP,Coeleft,timt1,timt2,time1,time2
       REAL*8 sum
       REAL*8 FockR(N3,N3)
       REAL*8 FockB(N3,N3)
       REAL*8 IntR(N0+1:N3,N0+1:N3,N0+1:N3,N0+1:N3)
       REAL*8 IntB(N0+1:N3,N0+1:N3,N0+1:N3,N0+1:N3)
       REAL*8 IntM(N0+1:N3,N0+1:N3,N0+1:N3,N0+1:N3)
       REAL*8 t1A(N1+1:N3,N0+1:N1)
       REAL*8 t1B(N2+1:N3,N0+1:N2)
       REAL*8 t2A(N1+1:N3,N1+1:N3,N0+1:N1,N0+1:N1)
       REAL*8 t2B(N2+1:N3,N1+1:N3,N0+1:N2,N0+1:N1)
       REAL*8 t2C(N2+1:N3,N2+1:N3,N0+1:N2,N0+1:N2)
       REAL*8 t3A(N1+1:N3,N1+1:N3,N1+1:N3,N0+1:N1,N0+1:N1,N0+1:N1)
       REAL*8 t3B(N2+1:N3,N1+1:N3,N1+1:N3,N0+1:N2,N0+1:N1,N0+1:N1)
       REAL*8 t3C(N2+1:N3,N2+1:N3,N1+1:N3,N0+1:N2,N0+1:N2,N0+1:N1)
       REAL*8 t3D(N2+1:N3,N2+1:N3,N2+1:N3,N0+1:N2,N0+1:N2,N0+1:N2)
C
!   REAL*8 t4A(N1+1:N3,N1+1:N3,N1+1:N3,N1+1:N3,
! & N0+1:N1,N0+1:N1,N0+1:N1,N0+1:N1)
!   REAL*8 t4B(N2+1:N3,N1+1:N3,N1+1:N3,N1+1:N3,
! & N0+1:N2,N0+1:N1,N0+1:N1,N0+1:N1)
!   REAL*8 t4C(N2+1:N3,N2+1:N3,N1+1:N3,N1+1:N3,
! & N0+1:N2,N0+1:N2,N0+1:N1,N0+1:N1)
!   REAL*8 t4D(N2+1:N3,N2+1:N3,N2+1:N3,N1+1:N3,
! & N0+1:N2,N0+1:N2,N0+1:N2,N0+1:N1)
!   REAL*8 t4E(N2+1:N3,N2+1:N3,N2+1:N3,N2+1:N3,
! & N0+1:N2,N0+1:N2,N0+1:N2,N0+1:N2)
!   REAL*8 V4A(K3*K3*K3*K3,K1*K1*K1*K1)
C
       REAL*8,ALLOCATABLE::t4A(:,:,:,:,:,:,:,:)
       REAL*8,ALLOCATABLE::t4B(:,:,:,:,:,:,:,:)
!   REAL*8,ALLOCATABLE::t4C(:,:,:,:,:,:,:,:)
!   REAL*8,ALLOCATABLE::t4D(:,:,:,:,:,:,:,:)
!   REAL*8,ALLOCATABLE::t4E(:,:,:,:,:,:,:,:)
       REAL*8,ALLOCATABLE::V4A(:,:,:,:,:,:,:,:)
C
       INTEGER ta,tb,tc,td,te
       PARAMETER(ta=29,tb=30,tc=31,td=32,te=33)
C
       ALLOCATE(t4A(N1+1:N3,N1+1:N3,N1+1:N3,N1+1:N3,
     & N0+1:N1,N0+1:N1,N0+1:N1,N0+1:N1))
       REWIND(ta)
       READ(ta)t4a

C
C
       DO i=N0+1,N1-3
       DO j=i+1,N1-2
       DO k=j+1,N1-1
       DO l=k+1,N1
       DO a=N1+1,N3-3
       DO b=a+1,N3-2
       DO c=b+1,N3-1
       DO d=c+1,N3
!
         t4A(d,c,b,a,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,b,a,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,c,a,b,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,b,c,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,a,c,b,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,b,d,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,c,d,b,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,b,c,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,d,c,b,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,c,a,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(d,b,a,c,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,c,d,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(a,b,d,c,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,d,a,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,c,a,d,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,d,c,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,a,c,d,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,c,a,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(b,d,a,c,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,b,a,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,d,a,b,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,b,d,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,a,d,b,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,l,k,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,l,k,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,l,i,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,l,i,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,i,k,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,i,k,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,i,l,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,i,l,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,l,j,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,l,j,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,i,j,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,i,j,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,j,k,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,j,k,i,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,j,i,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,j,i,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,j,l,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,j,l,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,k,l,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,k,l,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,k,i,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,k,i,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,k,j,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,d,a,k,j,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,l,k,j,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,l,k,i,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,l,i,j,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,l,i,k,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,i,k,j,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,i,k,l,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,i,l,j,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,i,l,k,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,l,j,k,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,l,j,i,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,i,j,k,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,i,j,l,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,j,k,l,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,j,k,i,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,j,i,l,k)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,j,i,k,l)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,j,l,k,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,j,l,i,k)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,k,l,j,i)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,k,l,i,j)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,k,i,j,l)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,k,i,l,j)= t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,k,j,l,i)=-t4A(d,c,b,a,l,k,j,i)
         t4A(c,b,a,d,k,j,i,l)= t4A(d,c,b,a,l,k,j,i)
       ENDDO
       ENDDO
       ENDDO
       ENDDO
       ENDDO
       ENDDO
       ENDDO
       ENDDO
       REWIND(ta)
       WRITE(ta)t4A
	CALL CPU_TIME(timt2)
C
       end
